-- MySQL Script generated by MySQL Workbench
-- Thu Jan  5 21:40:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema snowtricks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema snowtricks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `snowtricks` DEFAULT CHARACTER SET utf8 ;
USE `snowtricks` ;

-- -----------------------------------------------------
-- Table `snowtricks`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snowtricks`.`User` ;

CREATE TABLE IF NOT EXISTS `snowtricks`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `mdp` VARCHAR(50) NOT NULL,
  `photo` TINYTEXT NOT NULL,
  `role` ENUM('admin', 'user') NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `snowtricks`.`Figure`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snowtricks`.`Figure` ;

CREATE TABLE IF NOT EXISTS `snowtricks`.`Figure` (
  `name` VARCHAR(50) NOT NULL,
  `groupe` ENUM('1', '2', '3', '4') NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_Figure_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Figure_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `snowtricks`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `snowtricks`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snowtricks`.`Message` ;

CREATE TABLE IF NOT EXISTS `snowtricks`.`Message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` DATETIME NOT NULL,
  `message` LONGTEXT NOT NULL,
  `User_idUser` INT NOT NULL,
  `Figure_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Message_User_idx` (`User_idUser` ASC),
  INDEX `fk_Message_Figure1_idx` (`Figure_name` ASC),
  CONSTRAINT `fk_Message_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `snowtricks`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_Figure1`
    FOREIGN KEY (`Figure_name`)
    REFERENCES `snowtricks`.`Figure` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `snowtricks`.`Video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snowtricks`.`Video` ;

CREATE TABLE IF NOT EXISTS `snowtricks`.`Video` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `link` MEDIUMTEXT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `Figure_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Video_Figure1_idx` (`Figure_name` ASC),
  CONSTRAINT `fk_Video_Figure1`
    FOREIGN KEY (`Figure_name`)
    REFERENCES `snowtricks`.`Figure` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `snowtricks`.`Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `snowtricks`.`Image` ;

CREATE TABLE IF NOT EXISTS `snowtricks`.`Image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `Figure_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Image_Figure1_idx` (`Figure_name` ASC),
  CONSTRAINT `fk_Image_Figure1`
    FOREIGN KEY (`Figure_name`)
    REFERENCES `snowtricks`.`Figure` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
